plugins:
  abbreviations_plugin_enabled:
    default: true
    client: true
  abbreviations_plugin_list:
    default: IMHO:In My Honest Opinion|YMMV:Your Mileage May Vary|lol:Laughing Out Loud 
    client: true
